// Generated by gencpp from file gps/gps.msg
// DO NOT EDIT!


#ifndef GPS_MESSAGE_GPS_H
#define GPS_MESSAGE_GPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gps
{
template <class ContainerAllocator>
struct gps_
{
  typedef gps_<ContainerAllocator> Type;

  gps_()
    : Header()
    , GPSWeek()
    , GPSTime()
    , Heading()
    , Pitch()
    , Roll()
    , Lattitude()
    , Longitude()
    , Altitude()
    , Ve()
    , Vn()
    , Vu()
    , Baseline()
    , NSV1()
    , NSV2()
    , Status()
    , Cs()
    , CrLf()  {
    }
  gps_(const ContainerAllocator& _alloc)
    : Header(_alloc)
    , GPSWeek(_alloc)
    , GPSTime(_alloc)
    , Heading(_alloc)
    , Pitch(_alloc)
    , Roll(_alloc)
    , Lattitude(_alloc)
    , Longitude(_alloc)
    , Altitude(_alloc)
    , Ve(_alloc)
    , Vn(_alloc)
    , Vu(_alloc)
    , Baseline(_alloc)
    , NSV1(_alloc)
    , NSV2(_alloc)
    , Status(_alloc)
    , Cs(_alloc)
    , CrLf(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Header_type;
  _Header_type Header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _GPSWeek_type;
  _GPSWeek_type GPSWeek;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _GPSTime_type;
  _GPSTime_type GPSTime;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Heading_type;
  _Heading_type Heading;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Pitch_type;
  _Pitch_type Pitch;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Roll_type;
  _Roll_type Roll;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Lattitude_type;
  _Lattitude_type Lattitude;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Longitude_type;
  _Longitude_type Longitude;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Altitude_type;
  _Altitude_type Altitude;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Ve_type;
  _Ve_type Ve;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Vn_type;
  _Vn_type Vn;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Vu_type;
  _Vu_type Vu;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Baseline_type;
  _Baseline_type Baseline;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _NSV1_type;
  _NSV1_type NSV1;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _NSV2_type;
  _NSV2_type NSV2;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Status_type;
  _Status_type Status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Cs_type;
  _Cs_type Cs;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _CrLf_type;
  _CrLf_type CrLf;





  typedef boost::shared_ptr< ::gps::gps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gps::gps_<ContainerAllocator> const> ConstPtr;

}; // struct gps_

typedef ::gps::gps_<std::allocator<void> > gps;

typedef boost::shared_ptr< ::gps::gps > gpsPtr;
typedef boost::shared_ptr< ::gps::gps const> gpsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gps::gps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gps::gps_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gps::gps_<ContainerAllocator1> & lhs, const ::gps::gps_<ContainerAllocator2> & rhs)
{
  return lhs.Header == rhs.Header &&
    lhs.GPSWeek == rhs.GPSWeek &&
    lhs.GPSTime == rhs.GPSTime &&
    lhs.Heading == rhs.Heading &&
    lhs.Pitch == rhs.Pitch &&
    lhs.Roll == rhs.Roll &&
    lhs.Lattitude == rhs.Lattitude &&
    lhs.Longitude == rhs.Longitude &&
    lhs.Altitude == rhs.Altitude &&
    lhs.Ve == rhs.Ve &&
    lhs.Vn == rhs.Vn &&
    lhs.Vu == rhs.Vu &&
    lhs.Baseline == rhs.Baseline &&
    lhs.NSV1 == rhs.NSV1 &&
    lhs.NSV2 == rhs.NSV2 &&
    lhs.Status == rhs.Status &&
    lhs.Cs == rhs.Cs &&
    lhs.CrLf == rhs.CrLf;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gps::gps_<ContainerAllocator1> & lhs, const ::gps::gps_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gps

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gps::gps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps::gps_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gps::gps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gps::gps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps::gps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps::gps_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gps::gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a5aa90e42daffbd5cb5734c9beaf213";
  }

  static const char* value(const ::gps::gps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a5aa90e42daffbdULL;
  static const uint64_t static_value2 = 0x5cb5734c9beaf213ULL;
};

template<class ContainerAllocator>
struct DataType< ::gps::gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gps/gps";
  }

  static const char* value(const ::gps::gps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gps::gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Header\n"
"string GPSWeek\n"
"string GPSTime\n"
"string Heading\n"
"string Pitch\n"
"string Roll\n"
"string Lattitude\n"
"string Longitude\n"
"string Altitude\n"
"string Ve\n"
"string Vn\n"
"string Vu\n"
"string Baseline\n"
"string NSV1\n"
"string NSV2\n"
"string Status\n"
"string Cs\n"
"string CrLf\n"
;
  }

  static const char* value(const ::gps::gps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gps::gps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Header);
      stream.next(m.GPSWeek);
      stream.next(m.GPSTime);
      stream.next(m.Heading);
      stream.next(m.Pitch);
      stream.next(m.Roll);
      stream.next(m.Lattitude);
      stream.next(m.Longitude);
      stream.next(m.Altitude);
      stream.next(m.Ve);
      stream.next(m.Vn);
      stream.next(m.Vu);
      stream.next(m.Baseline);
      stream.next(m.NSV1);
      stream.next(m.NSV2);
      stream.next(m.Status);
      stream.next(m.Cs);
      stream.next(m.CrLf);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gps::gps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gps::gps_<ContainerAllocator>& v)
  {
    s << indent << "Header: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Header);
    s << indent << "GPSWeek: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.GPSWeek);
    s << indent << "GPSTime: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.GPSTime);
    s << indent << "Heading: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Heading);
    s << indent << "Pitch: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Pitch);
    s << indent << "Roll: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Roll);
    s << indent << "Lattitude: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Lattitude);
    s << indent << "Longitude: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Longitude);
    s << indent << "Altitude: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Altitude);
    s << indent << "Ve: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Ve);
    s << indent << "Vn: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Vn);
    s << indent << "Vu: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Vu);
    s << indent << "Baseline: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Baseline);
    s << indent << "NSV1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.NSV1);
    s << indent << "NSV2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.NSV2);
    s << indent << "Status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Status);
    s << indent << "Cs: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Cs);
    s << indent << "CrLf: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.CrLf);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPS_MESSAGE_GPS_H
